"""Generate the committed mkdocstrings API-reference source pages.

The generated Markdown is intentionally small: mkdocstrings renders signatures,
docstrings, and class members when MkDocs builds the site. Keeping the source
stubs in Git makes the inventory reviewable and lets CI prove that every
top-level public export has exactly one page.
"""

from __future__ import annotations

import argparse
import inspect
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
REFERENCE_DIR = ROOT / "docs" / "reference"
GENERATED_MARKER = "<!-- Generated by scripts/generate_api_reference.py; do not edit. -->"
GLOSSARY_LINK = "[glossary](../glossary.md)"


PUBLIC_API_GROUPS: tuple[tuple[str, tuple[str, ...]], ...] = (
    ("Package metadata", ("__version__",)),
    (
        "Fixed-k filters",
        (
            "select_mrmr",
            "select_jmi",
            "select_jmim",
            "select_cefsplus",
            "select_cefsplus_binary",
        ),
    ),
    (
        "Knockoff FDR",
        (
            "select_fdr",
            "KnockoffSelector",
            "KnockoffSelectionResult",
            "sample_knockoffs",
        ),
    ),
    ("Gaussian caches", ("FeatureCache", "build_cache", "select_cached")),
    (
        "Automatic k",
        (
            "AutoKConfig",
            "FeaturePathEvaluationResult",
            "evaluate_feature_path",
            "select_k_auto",
            "select_k_elbow",
            "select_k_penalized_objective",
            "select_k_posterior",
            "path_gain_pvalues",
            "select_k_changepoint",
            "select_k_chi2_stop",
            "select_k_forward_stop",
            "bootstrap_paths",
            "null_objective_paths",
            "select_k_perm_gap",
            "select_k_stability",
            "gaussian_cv_curves",
            "select_k_gaussian_cv",
            "select_k_xfit_objective",
            "select_k_knockoff_path",
            "xfit_objective_curves",
            "compute_objective_for_path",
        ),
    ),
    (
        "scikit-learn selector classes",
        (
            "MRMRSelector",
            "JMISelector",
            "JMIMSelector",
            "CEFSPlusSelector",
            "CEFSPlusBinarySelector",
        ),
    ),
    ("Result views", ("FilterSelectionResult", "SelectionView", "as_result")),
    ("Selector comparison", ("compare", "CompareResult")),
    (
        "Stability selection",
        ("StabilitySelector", "stability_regression", "stability_classif", "Stabilized"),
    ),
    (
        "Smart sampling",
        ("SmartSamplerConfig", "smart_sample", "panel_config", "cross_section_config"),
    ),
    (
        "Purged time-series CV",
        ("PurgedTimeSeriesSplit", "GroupPurgedTimeSeriesSplit"),
    ),
    (
        "Generic model selector",
        ("ModelSelector",),
    ),
    ("Permutation importance", ("permutation_importance",)),
    (
        "Boruta",
        ("BorutaSelector", "BorutaResult", "select_boruta", "select_boruta_shap"),
    ),
    (
        "Optional CatBoost",
        ("catboost_select", "catboost_regression", "catboost_classif"),
    ),
    ("Logging", ("set_verbosity",)),
)


def _public_exports() -> tuple[str, ...]:
    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    import sift

    return tuple(sift.__all__)


def _filename(name: str) -> str:
    return "version.md" if name == "__version__" else f"{name.lower()}.md"


def _canonical_identifier(name: str) -> str:
    if name == "__version__":
        return "sift"

    import sift

    obj = getattr(sift, name)
    module = inspect.getmodule(obj)
    if module is None or not module.__name__.startswith("sift"):
        raise RuntimeError(f"cannot resolve a SIFT source module for public export {name!r}")
    qualname = getattr(obj, "__qualname__", name)
    if "<locals>" in qualname:
        raise RuntimeError(f"public export {name!r} resolves to a local object")
    return f"{module.__name__}.{qualname}"


def _render_index(groups: tuple[tuple[str, tuple[str, ...]], ...]) -> str:
    lines = [
        GENERATED_MARKER,
        "# API Reference",
        "",
        "This reference is generated from the public objects in `sift.__all__` and",
        "rendered from their numpydoc docstrings by mkdocstrings. For selection",
        "guidance and complete workflows, use the",
        "[canonical manual](https://github.com/kmedved/sift/blob/main/DOCS.MD).",
        f"SIFT-specific terms are defined in the {GLOSSARY_LINK}.",
        "",
        "> **Rendering note:** the committed files in this directory are MkDocs",
        "> source pages. GitHub displays their `:::` directives rather than the",
        "> expanded signatures and docstrings. Install `.[docs]` and run",
        "> `mkdocs serve` from the repository root to browse the rendered reference.",
        "",
        "Do not edit the pages in this directory directly. Regenerate them with:",
        "",
        "```bash",
        "python scripts/generate_api_reference.py",
        "```",
    ]
    for heading, names in groups:
        lines.extend(("", f"## {heading}", ""))
        for name in names:
            lines.append(f"- [`sift.{name}`]({_filename(name)})")
    return "\n".join(lines) + "\n"


def _render_page(name: str) -> str:
    if name == "__version__":
        directive = """::: sift
    options:
      members:
        - __version__
      show_root_heading: false
"""
    else:
        directive = f"::: {_canonical_identifier(name)}\n"
    return (
        f"{GENERATED_MARKER}\n"
        f"# `sift.{name}`\n\n"
        f"Public import: `from sift import {name}`\n\n"
        f"SIFT-specific terms are defined in the {GLOSSARY_LINK}.\n\n"
        f"{directive}"
    )


def expected_files() -> dict[Path, str]:
    exports = _public_exports()
    grouped = tuple(name for _, names in PUBLIC_API_GROUPS for name in names)
    if len(grouped) != len(set(grouped)):
        raise RuntimeError("PUBLIC_API_GROUPS contains duplicate exports")
    if set(grouped) != set(exports):
        missing = sorted(set(exports) - set(grouped))
        extra = sorted(set(grouped) - set(exports))
        raise RuntimeError(f"PUBLIC_API_GROUPS mismatch: missing={missing}, extra={extra}")

    files = {REFERENCE_DIR / "index.md": _render_index(PUBLIC_API_GROUPS)}
    files.update(
        (REFERENCE_DIR / _filename(name), _render_page(name)) for name in exports
    )
    return files


def _check(expected: dict[Path, str]) -> int:
    actual_paths = set(REFERENCE_DIR.glob("*.md")) if REFERENCE_DIR.exists() else set()
    expected_paths = set(expected)
    stale = sorted(path.relative_to(ROOT) for path in actual_paths - expected_paths)
    missing = sorted(path.relative_to(ROOT) for path in expected_paths - actual_paths)
    changed = sorted(
        path.relative_to(ROOT)
        for path, content in expected.items()
        if path.is_file() and path.read_text(encoding="utf-8") != content
    )
    if stale or missing or changed:
        print(f"stale={stale}")
        print(f"missing={missing}")
        print(f"changed={changed}")
        return 1
    print(f"API reference is current ({len(expected) - 1} exports plus index).")
    return 0


def _write(expected: dict[Path, str]) -> None:
    REFERENCE_DIR.mkdir(parents=True, exist_ok=True)
    for path in REFERENCE_DIR.glob("*.md"):
        if path not in expected:
            path.unlink()
    for path, content in expected.items():
        path.write_text(content, encoding="utf-8")
    print(f"Generated {len(expected) - 1} API pages and {REFERENCE_DIR / 'index.md'}." )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when committed API-reference pages do not match the public surface",
    )
    args = parser.parse_args()
    expected = expected_files()
    if args.check:
        return _check(expected)
    _write(expected)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
