"""Generate the observed public data-type support matrix.

The matrix is not a wishlist. Every cell is the outcome of calling a public
selector entry point on a tiny fixture: supported, rejected, conditional, or
dependency-gated. Conditional cells retry a documented enabling option
(``cat_encoding="target_cv"``, KnockoffSelector ``loo_logit``, ``k="auto"``
with evaluate splits, ``ModelSelector`` searched count grids, or a
width-preserving sklearn encoding pipeline). Probes keep data-type
acceptance and encoding defaults intact, but they fix ``alpha=1.0`` for
stability (skipping automatic alpha search), CatBoost
``algorithm="prediction"`` with ``prefilter_k=None`` (skipping the expensive
SHAP/prefilter defaults), and ``ModelSelector(Ridge())`` because that class
requires an estimator (a disclosed probe baseline, not a library default).
Published rejected-cell notes are stable public-contract descriptions; raw
exception text is kept only on the attempt for diagnostics. The generator
does not change selector mathematics or public defaults.
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass, field
import inspect
from pathlib import Path
import sys
import traceback
import warnings

import numpy as np
import pandas as pd
from scipy import sparse
from sklearn.ensemble import RandomForestRegressor


ROOT = Path(__file__).resolve().parents[1]
DOC = ROOT / "docs" / "data-type-support.md"
GENERATED_MARKER = "<!-- Generated by scripts/generate_data_type_matrix.py; do not edit. -->"
TABLE_START = "<!-- data-type-matrix:start -->"
TABLE_END = "<!-- data-type-matrix:end -->"
NOTES_START = "<!-- data-type-notes:start -->"
NOTES_END = "<!-- data-type-notes:end -->"

SUPPORTED = "supported"
REJECTED = "rejected"
CONDITIONAL = "conditional"
DEPENDENCY_GATED = "dependency-gated"

STATUS_LABELS = {
    SUPPORTED: "yes",
    REJECTED: "no",
    CONDITIONAL: "cond",
    DEPENDENCY_GATED: "dep",
}

AXES = (
    "numeric_ndarray",
    "numeric_dataframe",
    "categorical",
    "sparse",
    "datetime_timedelta",
    "sample_weight",
    "groups",
    "time",
)

AXIS_HEADERS = {
    "numeric_ndarray": "ndarray",
    "numeric_dataframe": "DataFrame",
    "categorical": "categorical",
    "sparse": "sparse",
    "datetime_timedelta": "datetime/timedelta",
    "sample_weight": "weights",
    "groups": "groups",
    "time": "time",
}

N_ROWS = 32
N_FEATURES = 4
K = 2
SEED = 0


def _ensure_import_path() -> None:
    root = str(ROOT)
    if root not in sys.path:
        sys.path.insert(0, root)


@dataclass(frozen=True)
class Attempt:
    ok: bool
    error: str | None = None
    warnings: tuple[str, ...] = ()

    @property
    def summary(self) -> str:
        if self.ok:
            return "completed"
        assert self.error is not None
        first = self.error.strip().splitlines()[0]
        return first[:180]


class _DtypeTolerantRegressor:
    """Fitted stand-in that accepts mixed-dtype X so SIFT is the code under test.

    sklearn numeric estimators reject string and datetime columns in ``fit``,
    which would never reach ``permutation_importance``. This probe vehicle is
    a legitimate fitted estimator with ``predict``; it does not encode or
    select features.
    """

    def fit(self, X, y):
        y_arr = np.asarray(y, dtype=np.float64).reshape(-1)
        self.constant_ = float(np.mean(y_arr)) if y_arr.size else 0.0
        return self

    def predict(self, X):
        n = int(X.shape[0])
        return np.full(n, self.constant_, dtype=np.float64)


@dataclass(frozen=True)
class Cell:
    entry: str
    axis: str
    status: str
    note: str
    default: Attempt
    enabled: Attempt | None = None


@dataclass
class Payload:
    X: object
    y: np.ndarray
    y_binary: np.ndarray
    sample_weight: np.ndarray | None = None
    groups: np.ndarray | None = None
    time: np.ndarray | None = None
    cat_features: list[str] | None = None
    feature_names: list[str] = field(default_factory=list)
    frame: pd.DataFrame | None = None


def _base_numeric(n: int = N_ROWS, p: int = N_FEATURES) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    rng = np.random.default_rng(SEED)
    X = rng.normal(size=(n, p))
    X[:, 0] = np.linspace(-1.0, 1.0, n)
    y = X[:, 0] + 0.15 * X[:, 1] + 0.05 * rng.normal(size=n)
    y_binary = (y > np.median(y)).astype(np.int64)
    return X, y, y_binary


def _names(p: int = N_FEATURES) -> list[str]:
    return [f"x{i}" for i in range(p)]


def make_payload(axis: str) -> Payload:
    X, y, y_binary = _base_numeric()
    names = _names()
    n = X.shape[0]
    groups = np.repeat(np.arange(4, dtype=np.int64), n // 4)
    time = np.arange(n, dtype=np.int64)
    weights = np.linspace(0.5, 1.5, n)
    frame = pd.DataFrame(X, columns=names)

    if axis == "numeric_ndarray":
        return Payload(X=X, y=y, y_binary=y_binary, feature_names=names)
    if axis == "numeric_dataframe":
        return Payload(
            X=frame.copy(),
            y=y,
            y_binary=y_binary,
            feature_names=names,
            frame=frame.copy(),
        )
    if axis == "categorical":
        cats = np.array(["red", "blue", "green", "gold"], dtype=object)
        labeled = frame.copy()
        labeled["city"] = cats[np.arange(n) % 4]
        return Payload(
            X=labeled,
            y=y,
            y_binary=y_binary,
            feature_names=list(labeled.columns),
            cat_features=["city"],
            frame=labeled,
        )
    if axis == "sparse":
        return Payload(
            X=sparse.csr_matrix(X),
            y=y,
            y_binary=y_binary,
            feature_names=names,
        )
    if axis == "datetime_timedelta":
        labeled = frame.copy()
        labeled["when"] = pd.date_range("2024-01-01", periods=n, freq="D")
        labeled["elapsed"] = pd.to_timedelta(np.arange(n), unit="h")
        return Payload(
            X=labeled,
            y=y,
            y_binary=y_binary,
            feature_names=list(labeled.columns),
            frame=labeled,
        )
    if axis == "sample_weight":
        return Payload(
            X=frame.copy(),
            y=y,
            y_binary=y_binary,
            sample_weight=weights,
            feature_names=names,
            frame=frame.copy(),
        )
    if axis == "groups":
        labeled = frame.copy()
        labeled["entity"] = groups
        return Payload(
            X=frame.copy(),
            y=y,
            y_binary=y_binary,
            groups=groups,
            feature_names=names,
            frame=labeled,
        )
    if axis == "time":
        stamps = pd.date_range("2024-01-01", periods=n, freq="D")
        labeled = frame.copy()
        labeled["as_of"] = stamps
        return Payload(
            X=frame.copy(),
            y=y,
            y_binary=y_binary,
            time=stamps.to_numpy(),
            feature_names=names,
            frame=labeled,
        )
    raise ValueError(f"unknown axis {axis!r}")


def _run(call) -> Attempt:
    with warnings.catch_warnings(record=True) as caught:
        warnings.simplefilter("always")
        try:
            call()
        except Exception as exc:
            return Attempt(
                ok=False,
                error=f"{type(exc).__name__}: {exc}",
                warnings=tuple(str(item.message) for item in caught),
            )
        return Attempt(
            ok=True,
            warnings=tuple(str(item.message) for item in caught),
        )


def _is_missing_dependency(attempt: Attempt, extra: str | None) -> bool:
    if extra is None or attempt.ok or attempt.error is None:
        return False
    text = attempt.error.lower()
    if extra == "catboost":
        return "catboost" in text and (
            text.startswith("importerror")
            or "modulenotfounderror" in text
            or "requires catboost" in text
        )
    if extra == "shap":
        # Do not match the substring "import" inside "importance".
        return "shap" in text and (
            text.startswith("importerror")
            or "modulenotfounderror" in text
            or "shap package" in text
        )
    if extra == "category_encoders":
        return "category_encoders" in text or "categorical encoding" in text
    return extra.lower() in text and (
        text.startswith("importerror") or "modulenotfounderror" in text
    )


def _accepts(callable_obj, name: str) -> bool:
    try:
        return name in inspect.signature(callable_obj).parameters
    except (TypeError, ValueError):
        return False


def _auto_k_config(*, groups: bool) -> object:
    from sift import AutoKConfig

    return AutoKConfig(
        k_method="evaluate",
        strategy="group_cv" if groups else "time_holdout",
        min_k=1,
        max_k=K,
        n_splits=2,
        val_frac=0.25,
    )


def _y(payload: Payload, binary: bool) -> np.ndarray:
    return payload.y_binary if binary else payload.y


def _filter_function_kwargs(
    fn,
    payload: Payload,
    *,
    binary: bool,
    auto: bool,
    cat_encoding: str | None,
    extra: dict,
) -> dict:
    kwargs = {
        "k": "auto" if auto else K,
        "verbose": False,
        "subsample": None,
        "random_state": SEED,
        **extra,
    }
    if _accepts(fn, "task") and "task" not in kwargs and not binary:
        kwargs["task"] = "regression"
    if payload.sample_weight is not None:
        kwargs["sample_weight"] = payload.sample_weight
    if payload.groups is not None:
        kwargs["groups"] = payload.groups
    if payload.time is not None:
        kwargs["time"] = payload.time
    if cat_encoding is not None:
        kwargs["cat_encoding"] = cat_encoding
        if payload.cat_features is not None:
            kwargs["cat_features"] = payload.cat_features
    if auto:
        kwargs["auto_k_config"] = _auto_k_config(groups=payload.groups is not None)
    return kwargs


def call_filter_function(
    fn,
    payload: Payload,
    *,
    binary: bool = False,
    auto: bool = False,
    cat_encoding: str | None = None,
    extra: dict | None = None,
) -> None:
    kwargs = _filter_function_kwargs(
        fn,
        payload,
        binary=binary,
        auto=auto,
        cat_encoding=cat_encoding,
        extra=extra or {},
    )
    fn(payload.X, _y(payload, binary), **kwargs)


def call_filter_class(
    cls,
    payload: Payload,
    *,
    binary: bool = False,
    auto: bool = False,
    cat_encoding: str | None = None,
    extra: dict | None = None,
) -> None:
    ctor = {
        "k": "auto" if auto else K,
        "verbose": False,
        "subsample": None,
        "random_state": SEED,
        **(extra or {}),
    }
    if _accepts(cls, "task") and "task" not in ctor and not binary:
        ctor["task"] = "regression"
    if cat_encoding is not None:
        ctor["cat_encoding"] = cat_encoding
        if payload.cat_features is not None:
            ctor["cat_features"] = payload.cat_features
    if auto:
        ctor["auto_k_config"] = _auto_k_config(groups=payload.groups is not None)
    fit_kwargs = {}
    if payload.sample_weight is not None:
        fit_kwargs["sample_weight"] = payload.sample_weight
    if payload.groups is not None:
        fit_kwargs["groups"] = payload.groups
    if payload.time is not None:
        fit_kwargs["time"] = payload.time
    cls(**ctor).fit(payload.X, _y(payload, binary), **fit_kwargs)


def call_select_fdr(payload: Payload) -> None:
    from sift import select_fdr

    kwargs = {
        "q": 0.5,
        "n_draws": 1,
        "subsample": None,
        "random_state": SEED,
        "verbose": False,
    }
    if payload.sample_weight is not None:
        kwargs["sample_weight"] = payload.sample_weight
    if payload.groups is not None:
        kwargs["groups"] = payload.groups
    if payload.time is not None:
        kwargs["time"] = payload.time
    select_fdr(payload.X, payload.y, **kwargs)


def call_knockoff_selector(
    payload: Payload,
    *,
    cat_encoding: str | None = None,
) -> None:
    from sift import KnockoffSelector

    ctor = {"q": 0.5, "n_draws": 1, "verbose": False, "random_state": SEED}
    if cat_encoding is not None:
        ctor["cat_encoding"] = cat_encoding
        if payload.cat_features is not None:
            ctor["cat_features"] = payload.cat_features
    fit_kwargs = {}
    if payload.sample_weight is not None:
        fit_kwargs["sample_weight"] = payload.sample_weight
    if payload.groups is not None:
        fit_kwargs["groups"] = payload.groups
    if payload.time is not None:
        fit_kwargs["time"] = payload.time
    y = payload.y_binary if cat_encoding == "loo_logit" else payload.y
    KnockoffSelector(**ctor).fit(payload.X, y, **fit_kwargs)


def call_boruta(
    payload: Payload,
    *,
    shap: bool = False,
    cat_encoding: str | None = None,
    as_class: bool = False,
    estimator=None,
) -> None:
    from sift import BorutaSelector, select_boruta, select_boruta_shap

    kwargs = {
        "max_iter": 1,
        "n_estimators": 4,
        "early_stop_rounds": 1,
        "resolve_tentative": False,
        "verbose": False,
        "random_state": SEED,
    }
    if cat_encoding is not None:
        kwargs["cat_encoding"] = cat_encoding
        if payload.cat_features is not None:
            kwargs["cat_features"] = payload.cat_features
    if estimator is not None:
        kwargs["estimator"] = estimator
    if payload.sample_weight is not None:
        kwargs["sample_weight"] = payload.sample_weight
    if payload.groups is not None:
        kwargs["groups"] = payload.groups
    if payload.time is not None:
        kwargs["time"] = payload.time
    if shap:
        select_boruta_shap(payload.X, payload.y, **kwargs)
        return
    if as_class:
        sample_weight = kwargs.pop("sample_weight", None)
        groups = kwargs.pop("groups", None)
        time = kwargs.pop("time", None)
        BorutaSelector(**kwargs).fit(
            payload.X,
            payload.y,
            sample_weight=sample_weight,
            groups=groups,
            time=time,
        )
        return
    select_boruta(payload.X, payload.y, **kwargs)


def call_stability(
    payload: Payload,
    *,
    kind: str,
) -> None:
    from sift import StabilitySelector, stability_classif, stability_regression

    common = {
        "n_bootstrap": 2,
        "n_jobs": 1,
        "alpha": 1.0,
        "verbose": False,
        "random_state": SEED,
        "store_coefs": False,
    }
    fit_kwargs = {}
    if payload.sample_weight is not None:
        fit_kwargs["sample_weight"] = payload.sample_weight
    if payload.groups is not None:
        fit_kwargs["groups"] = payload.groups
    if payload.time is not None:
        fit_kwargs["time"] = payload.time
    y = payload.y_binary if kind == "classif" else payload.y
    if kind == "selector":
        StabilitySelector(task="regression", **common).fit(payload.X, y, **fit_kwargs)
        return
    fn = stability_classif if kind == "classif" else stability_regression
    fn(payload.X, y, k=K, **common, **fit_kwargs)


def _width_preserving_ordinal_ridge():
    """Encode non-numeric columns without expanding width, then Ridge.

    ``make_column_selector`` follows whatever columns the current fit still
    has, so RFE subsets keep working. Permutation importance ranks the raw
    input columns. This is a disclosed ``ModelSelector`` probe pipeline, not
    a SIFT default.
    """
    from sklearn.compose import ColumnTransformer, make_column_selector
    from sklearn.linear_model import Ridge
    from sklearn.pipeline import make_pipeline
    from sklearn.preprocessing import OrdinalEncoder

    encoder = ColumnTransformer(
        [
            (
                "cat",
                OrdinalEncoder(
                    handle_unknown="use_encoded_value",
                    unknown_value=-1,
                ),
                make_column_selector(dtype_exclude=np.number),
            )
        ],
        remainder="passthrough",
        verbose_feature_names_out=False,
    )
    return make_pipeline(encoder, Ridge())


def call_model_selector(payload: Payload, **mode) -> None:
    from sklearn.linear_model import Ridge
    from sift import ModelSelector

    search_counts = bool(mode.get("search_counts"))
    encode_categorical = bool(mode.get("encode_categorical"))
    if encode_categorical:
        if not isinstance(payload.X, pd.DataFrame):
            raise TypeError("categorical ModelSelector probe requires a DataFrame")
        estimator = _width_preserving_ordinal_ridge()
        importance = "permutation"
    else:
        estimator = Ridge()
        importance = "auto"
    selector = ModelSelector(
        estimator,
        n_features_to_select=[1, K] if search_counts else K,
        importance=importance,
        random_state=SEED,
        verbose=False,
    )
    kwargs = {}
    if payload.sample_weight is not None:
        kwargs["sample_weight"] = payload.sample_weight
    if payload.groups is not None:
        kwargs["groups"] = payload.groups
    if payload.time is not None:
        kwargs["time"] = payload.time
    selector.fit(payload.X, payload.y, **kwargs)


def call_stabilized(payload: Payload, **_mode) -> None:
    from sift import CEFSPlusSelector, Stabilized

    inner = CEFSPlusSelector(k=K, verbose=False, subsample=None, random_state=SEED)
    estimator = Stabilized(
        inner,
        n_resamples=2,
        resample="half",
        threshold=0.0,
        random_state=SEED,
        verbose=False,
    )
    kwargs = {}
    if payload.sample_weight is not None:
        kwargs["sample_weight"] = payload.sample_weight
    if payload.groups is not None:
        kwargs["groups"] = payload.groups
    if payload.time is not None:
        kwargs["time"] = payload.time
    estimator.fit(payload.X, payload.y, **kwargs)


def call_permutation(payload: Payload) -> None:
    from sift import permutation_importance

    model = _DtypeTolerantRegressor().fit(payload.X, payload.y)
    kwargs = {"n_repeats": 1, "n_jobs": 1, "random_state": SEED}
    if payload.sample_weight is not None:
        kwargs["sample_weight"] = payload.sample_weight
    if payload.groups is not None:
        kwargs["groups"] = payload.groups
    if payload.time is not None:
        kwargs["time"] = payload.time
    permutation_importance(model, payload.X, payload.y, **kwargs)


def call_smart_sample(payload: Payload) -> None:
    from sift import smart_sample

    if not isinstance(payload.X, pd.DataFrame):
        smart_sample(
            payload.X,
            payload.feature_names,
            "y",
            random_state=SEED,
            verbose=False,
            sample_frac=0.5,
            min_per_group=1,
        )
        return

    df = payload.frame.copy() if payload.frame is not None else payload.X.copy()
    y_col = "y"
    df[y_col] = payload.y
    feature_cols = [name for name in df.columns if name not in {y_col, "entity", "as_of"}]
    kwargs = {
        "random_state": SEED,
        "verbose": False,
        "sample_frac": 0.5,
        "min_per_group": 1,
    }
    if payload.groups is not None:
        kwargs["group_col"] = "entity"
    if payload.time is not None:
        kwargs["time_col"] = "as_of"
    if payload.sample_weight is not None:
        kwargs["sample_weight"] = payload.sample_weight
    smart_sample(df, feature_cols, y_col, **kwargs)


def call_select_cached(payload: Payload) -> None:
    from sift import build_cache, select_cached

    cache_kwargs = {"subsample": None}
    if payload.sample_weight is not None:
        cache_kwargs["sample_weight"] = payload.sample_weight
    cache = build_cache(payload.X, **cache_kwargs)
    kwargs = {"k": K}
    if payload.groups is not None:
        kwargs["groups"] = payload.groups
    if payload.time is not None:
        kwargs["time"] = payload.time
    select_cached(cache, payload.y, **kwargs)


def call_catboost(
    payload: Payload,
    *,
    kind: str,
) -> None:
    import sift

    kwargs = {
        "k": K,
        "n_splits": 2,
        "prefilter_k": None,
        "n_estimators": 8,
        "algorithm": "prediction",
        "steps": 1,
        "train_early_stopping_rounds": 1,
        "n_jobs": 1,
        "random_state": SEED,
        "verbose": False,
    }
    if payload.sample_weight is not None:
        kwargs["sample_weight"] = payload.sample_weight
    if payload.groups is not None:
        kwargs["groups"] = payload.groups
    if payload.time is not None:
        kwargs["time"] = payload.time
    if kind == "select":
        sift.catboost_select(payload.X, _y(payload, False), task="regression", **kwargs)
        return
    if kind == "regression":
        sift.catboost_regression(payload.X, payload.y, **kwargs)
        return
    sift.catboost_classif(payload.X, payload.y_binary, **kwargs)


@dataclass(frozen=True)
class Entry:
    name: str
    extra: str | None
    supports_auto_k: bool
    supports_target_cv: bool
    call: object


def entries() -> tuple[Entry, ...]:
    import sift

    filter_extra = {"subsample": None, "random_state": SEED}
    return (
        Entry(
            "select_mrmr",
            None,
            True,
            True,
            lambda payload, **mode: call_filter_function(
                sift.select_mrmr,
                payload,
                extra=filter_extra,
                **mode,
            ),
        ),
        Entry(
            "select_jmi",
            None,
            True,
            True,
            lambda payload, **mode: call_filter_function(
                sift.select_jmi,
                payload,
                extra=filter_extra,
                **mode,
            ),
        ),
        Entry(
            "select_jmim",
            None,
            True,
            True,
            lambda payload, **mode: call_filter_function(
                sift.select_jmim,
                payload,
                extra=filter_extra,
                **mode,
            ),
        ),
        Entry(
            "select_cefsplus",
            None,
            True,
            True,
            lambda payload, **mode: call_filter_function(
                sift.select_cefsplus, payload, extra=filter_extra, **mode
            ),
        ),
        Entry(
            "select_cefsplus_binary",
            None,
            True,
            True,
            lambda payload, **mode: call_filter_function(
                sift.select_cefsplus_binary,
                payload,
                binary=True,
                extra=filter_extra,
                **mode,
            ),
        ),
        Entry(
            "MRMRSelector",
            None,
            True,
            True,
            lambda payload, **mode: call_filter_class(
                sift.MRMRSelector,
                payload,
                **mode,
            ),
        ),
        Entry(
            "JMISelector",
            None,
            True,
            True,
            lambda payload, **mode: call_filter_class(
                sift.JMISelector, payload, **mode
            ),
        ),
        Entry(
            "JMIMSelector",
            None,
            True,
            True,
            lambda payload, **mode: call_filter_class(
                sift.JMIMSelector, payload, **mode
            ),
        ),
        Entry(
            "CEFSPlusSelector",
            None,
            True,
            True,
            lambda payload, **mode: call_filter_class(
                sift.CEFSPlusSelector, payload, **mode
            ),
        ),
        Entry(
            "CEFSPlusBinarySelector",
            None,
            True,
            True,
            lambda payload, **mode: call_filter_class(
                sift.CEFSPlusBinarySelector, payload, binary=True, **mode
            ),
        ),
        Entry("select_fdr", None, False, False, call_select_fdr),
        Entry("KnockoffSelector", None, False, False, call_knockoff_selector),
        Entry("select_cached", None, False, False, call_select_cached),
        Entry(
            "select_boruta",
            None,
            False,
            True,
            lambda payload, **mode: call_boruta(payload, **mode),
        ),
        Entry(
            "BorutaSelector",
            None,
            False,
            True,
            lambda payload, **mode: call_boruta(payload, as_class=True, **mode),
        ),
        Entry(
            "select_boruta_shap",
            "catboost",
            False,
            True,
            lambda payload, **mode: call_boruta(payload, shap=True, **mode),
        ),
        Entry(
            "StabilitySelector",
            None,
            False,
            False,
            lambda payload, **mode: call_stability(payload, kind="selector", **mode),
        ),
        Entry(
            "stability_regression",
            None,
            False,
            False,
            lambda payload, **mode: call_stability(payload, kind="regression", **mode),
        ),
        Entry(
            "stability_classif",
            None,
            False,
            False,
            lambda payload, **mode: call_stability(payload, kind="classif", **mode),
        ),
        Entry("Stabilized", None, False, False, call_stabilized),
        Entry("ModelSelector", None, False, False, call_model_selector),
        Entry("permutation_importance", None, False, False, call_permutation),
        Entry("smart_sample", None, False, False, call_smart_sample),
        Entry(
            "catboost_select",
            "catboost",
            False,
            False,
            lambda payload, **mode: call_catboost(payload, kind="select", **mode),
        ),
        Entry(
            "catboost_regression",
            "catboost",
            False,
            False,
            lambda payload, **mode: call_catboost(payload, kind="regression", **mode),
        ),
        Entry(
            "catboost_classif",
            "catboost",
            False,
            False,
            lambda payload, **mode: call_catboost(payload, kind="classif", **mode),
        ),
    )


def _enabled_mode(axis: str, entry: Entry) -> dict | None:
    if axis == "categorical" and entry.supports_target_cv:
        return {"cat_encoding": "target_cv"}
    if axis == "categorical" and entry.name == "KnockoffSelector":
        return {"cat_encoding": "loo_logit"}
    if axis == "categorical" and entry.name == "ModelSelector":
        return {"encode_categorical": True}
    if axis in {"groups", "time"} and entry.supports_auto_k:
        return {"auto": True}
    if axis in {"groups", "time"} and entry.name == "ModelSelector":
        return {"search_counts": True}
    return None


def _shap_estimator():
    return RandomForestRegressor(n_estimators=4, max_depth=2, random_state=SEED)


def _shap_probe(entry: Entry, payload: Payload, enabled_mode: dict | None = None) -> Attempt:
    kwargs = {"estimator": _shap_estimator()}
    if enabled_mode:
        kwargs.update(enabled_mode)
    return _run(lambda: entry.call(payload, **kwargs))


CATBOOST_ENTRIES = frozenset(
    {"catboost_select", "catboost_regression", "catboost_classif"}
)
CATBOOST_PUBLISHED_STATUS = {
    "numeric_ndarray": REJECTED,
    "numeric_dataframe": DEPENDENCY_GATED,
    "categorical": DEPENDENCY_GATED,
    "sparse": REJECTED,
    "datetime_timedelta": REJECTED,
    "sample_weight": DEPENDENCY_GATED,
    "groups": DEPENDENCY_GATED,
    "time": DEPENDENCY_GATED,
}


def _stable_note(
    entry: Entry,
    axis: str,
    status: str,
    *,
    default: Attempt,
    enabled: Attempt | None,
) -> str:
    if status == CONDITIONAL and axis == "categorical" and entry.name == "KnockoffSelector":
        return (
            'baseline `cat_encoding="none"` rejects string/category columns; '
            '`cat_encoding="loo_logit"` completes with a UserWarning and '
            "`fdr_control='none'` because supervised encoding drops the Model-X claim"
        )
    if status == CONDITIONAL and axis == "categorical" and entry.name == "ModelSelector":
        return (
            "the disclosed Ridge baseline cannot consume string columns; a "
            "width-preserving sklearn OrdinalEncoder pipeline with "
            "`importance='permutation'` completes. Categorical handling is "
            "estimator-dependent and is not a ModelSelector encoding default"
        )
    if status == CONDITIONAL and axis == "categorical":
        return (
            'baseline `cat_encoding="none"` rejects string/category columns; '
            '`cat_encoding="target_cv"` encodes them without extras'
        )
    if status == CONDITIONAL and axis in {"groups", "time"}:
        if entry.name == "ModelSelector":
            return (
                "an explicit integer `n_features_to_select` rejects unused "
                f"`{axis}` metadata; a searched count grid with the default "
                f"reusable `{axis}` CV is accepted"
            )
        return (
            "fixed-k baseline calls reject row context; "
            f'`k="auto"` with evaluate `{axis}` splits is accepted'
        )
    if status == SUPPORTED and axis == "sample_weight" and entry.name == "select_cached":
        return (
            "weights belong on `build_cache(X, sample_weight=w, subsample=None)`; "
            "`select_cached` has no call-time `sample_weight` because the cache "
            "already stores row weights"
        )
    if status == SUPPORTED and axis in {"categorical", "datetime_timedelta"} and (
        entry.name == "permutation_importance"
    ):
        return (
            "`permutation_importance` forwards X to the fitted model; with a "
            "dtype-tolerant fitted estimator the public call completes. Support "
            "is model-dependent"
        )
    if status == SUPPORTED and axis == "datetime_timedelta" and entry.name == "smart_sample":
        return (
            "the baseline call completes after coercing datetime/timedelta "
            "feature columns to epoch-scale float32 values, which can be "
            "lossy; convert them to numeric features explicitly"
        )
    if status == SUPPORTED and axis == "categorical":
        return "string/category columns are consumed by the seeded baseline call"
    if status == SUPPORTED and axis == "sample_weight":
        return "sample_weight is accepted on the seeded baseline call"
    if status == SUPPORTED and axis in {"groups", "time"}:
        if entry.name == "smart_sample":
            col = "group_col" if axis == "groups" else "time_col"
            return (
                f"`{axis}` is accepted as `{col}` on `SmartSamplerConfig`, "
                f"not as a `{axis}=` array argument"
            )
        return f"`{axis}` is accepted on the seeded baseline call"
    if status == SUPPORTED:
        return "seeded, bounded baseline call completed on the tiny fixture"
    if status == DEPENDENCY_GATED:
        if entry.name == "select_boruta_shap" and axis == "categorical":
            return (
                'baseline `cat_encoding="none"` rejects string/category columns; '
                '`cat_encoding="target_cv"` is required, and the SHAP backend '
                "then needs CatBoost or the `shap` package with an explicit "
                "compatible estimator"
            )
        if entry.name in CATBOOST_ENTRIES:
            return (
                "requires the optional `catboost` extra; installing it unlocks "
                "this axis"
            )
        return STABLE_EXTRA_NOTES[entry.name]
    if axis == "datetime_timedelta":
        return (
            "datetime/timedelta feature columns are rejected; convert them to "
            "numeric features explicitly"
        )
    if axis == "sparse":
        if entry.name == "permutation_importance":
            return (
                "sparse matrices are rejected independently of the fitted model; "
                "X must be a 2D dense array or pandas DataFrame"
            )
        if entry.name == "smart_sample":
            return "requires a pandas DataFrame; sparse input is rejected"
        return (
            "sparse input is rejected; pass a dense NumPy array or pandas DataFrame"
        )
    if axis == "categorical":
        if entry.name in {"select_fdr", "select_cached"}:
            return (
                "non-numeric columns are rejected; encode categoricals before "
                "the Gaussian estimator"
            )
        if entry.name == "KnockoffSelector":
            return (
                'baseline `cat_encoding="none"` rejects string/category columns; '
                "`target_cv` is not accepted"
            )
        if entry.name in {
            "StabilitySelector",
            "stability_regression",
            "stability_classif",
            "Stabilized",
            "smart_sample",
        }:
            return "string/category columns are not accepted as numeric features"
        return "string/category columns are rejected on the seeded baseline call"
    if axis in {"groups", "time"}:
        if entry.name == "select_fdr":
            return f"the public function has no `{axis}` argument"
        if entry.name == "KnockoffSelector":
            if axis == "groups":
                return (
                    "row groups are rejected; use `feature_groups` for grouped "
                    "discoveries"
                )
            return "time-aware fitting is rejected"
        if entry.name == "select_cached":
            return (
                "`select_cached` has no groups or time argument; row context is "
                "not part of the cache-backed selector"
            )
        if entry.name == "Stabilized":
            return (
                f"`{axis}` is consumed by resample='blocks' (which needs both "
                "groups and time) or forwarded to bases that accept row context; "
                "unused row metadata is rejected"
            )
        return f"`{axis}` is rejected on the seeded baseline call"
    if axis == "numeric_ndarray":
        if entry.name == "smart_sample":
            return "requires a pandas DataFrame; ndarray input is rejected"
        return "ndarray input is rejected; pass a pandas DataFrame"
    if axis == "sample_weight":
        if entry.name == "smart_sample":
            return (
                "there is no input `sample_weight` argument; the sampler writes "
                "its own `sample_weight` column"
            )
        return "sample_weight is rejected on the seeded baseline call"
    return "the public call raised"


def classify_cell(entry: Entry, axis: str) -> Cell:
    payload = make_payload(axis)
    default = _run(lambda: entry.call(payload))
    if _is_missing_dependency(default, entry.extra):
        enabled = None
        if entry.name == "select_boruta_shap":
            enabled = _shap_probe(entry, payload)
        return Cell(
            entry.name,
            axis,
            DEPENDENCY_GATED,
            _stable_note(
                entry, axis, DEPENDENCY_GATED, default=default, enabled=enabled
            ),
            default,
            enabled,
        )

    enabled_mode = _enabled_mode(axis, entry)
    enabled = None
    if not default.ok and enabled_mode is not None:
        enabled = _run(lambda: entry.call(payload, **enabled_mode))
        if enabled.ok:
            return Cell(
                entry.name,
                axis,
                CONDITIONAL,
                _stable_note(
                    entry, axis, CONDITIONAL, default=default, enabled=enabled
                ),
                default,
                enabled,
            )
        if _is_missing_dependency(enabled, entry.extra):
            if entry.name == "select_boruta_shap":
                enabled = _shap_probe(entry, payload, enabled_mode)
            return Cell(
                entry.name,
                axis,
                DEPENDENCY_GATED,
                _stable_note(
                    entry,
                    axis,
                    DEPENDENCY_GATED,
                    default=default,
                    enabled=enabled,
                ),
                default,
                enabled,
            )

    if default.ok:
        return Cell(
            entry.name,
            axis,
            SUPPORTED,
            _stable_note(entry, axis, SUPPORTED, default=default, enabled=None),
            default,
        )

    return Cell(
        entry.name,
        axis,
        REJECTED,
        _stable_note(entry, axis, REJECTED, default=default, enabled=enabled),
        default,
        enabled,
    )


def probe_all() -> list[Cell]:
    _ensure_import_path()
    cells = []
    for entry in entries():
        for axis in AXES:
            cells.append(classify_cell(entry, axis))
    return cells


STABLE_EXTRA_NOTES = {
    "select_boruta_shap": (
        "the default SHAP backend needs CatBoost; without CatBoost, an explicit "
        "non-CatBoost estimator still requires the optional `shap` package"
    ),
}


def publish_cell(cell: Cell, entry: Entry) -> Cell:
    """Publish one environment-stable contract per extra-gated entry.

    For the three CatBoost selectors, publish the known post-install contract
    in every environment: ndarray/sparse/datetime-timedelta are rejected;
    DataFrame/categorical/weights/groups/time are dependency-gated. ``dep``
    means installing the extra can unlock the axis.
    """
    if entry.name in CATBOOST_ENTRIES:
        status = CATBOOST_PUBLISHED_STATUS[cell.axis]
        return Cell(
            cell.entry,
            cell.axis,
            status,
            _stable_note(
                entry,
                cell.axis,
                status,
                default=cell.default,
                enabled=cell.enabled,
            ),
            cell.default,
            cell.enabled,
        )
    if entry.extra is None or cell.status == REJECTED:
        return cell
    return Cell(
        cell.entry,
        cell.axis,
        DEPENDENCY_GATED,
        _stable_note(
            entry,
            cell.axis,
            DEPENDENCY_GATED,
            default=cell.default,
            enabled=cell.enabled,
        ),
        cell.default,
        cell.enabled,
    )


def probe_published() -> list[Cell]:
    _ensure_import_path()
    by_name = {entry.name: entry for entry in entries()}
    return [publish_cell(cell, by_name[cell.entry]) for cell in probe_all()]


def _status_grid(cells: list[Cell]) -> dict[tuple[str, str], Cell]:
    return {(cell.entry, cell.axis): cell for cell in cells}


def render_table(cells: list[Cell]) -> str:
    grid = _status_grid(cells)
    header = ["entry", *[AXIS_HEADERS[axis] for axis in AXES]]
    lines = [
        "| " + " | ".join(header) + " |",
        "| --- | " + " | ".join(["---"] * len(AXES)) + " |",
    ]
    seen: list[str] = []
    for cell in cells:
        if cell.entry not in seen:
            seen.append(cell.entry)
    for name in seen:
        row = [f"`{name}`"]
        for axis in AXES:
            row.append(STATUS_LABELS[grid[(name, axis)].status])
        lines.append("| " + " | ".join(row) + " |")
    return "\n".join(lines)


def render_notes(cells: list[Cell]) -> str:
    lines = [
        "| entry | axis | status | observed behavior |",
        "| --- | --- | --- | --- |",
    ]
    for cell in cells:
        if cell.status == SUPPORTED and cell.axis in {
            "numeric_ndarray",
            "numeric_dataframe",
        }:
            continue
        if (
            cell.status == SUPPORTED
            and cell.axis == "sample_weight"
            and cell.entry != "select_cached"
        ):
            continue
        lines.append(
            "| "
            + " | ".join(
                (
                    f"`{cell.entry}`",
                    AXIS_HEADERS[cell.axis],
                    cell.status,
                    cell.note.replace("|", "\\|"),
                )
            )
            + " |"
        )
    return "\n".join(lines)


def render_page(cells: list[Cell]) -> str:
    return "\n".join(
        [
            GENERATED_MARKER,
            "# Data-Type Support",
            "",
            "This page is an observed public-behavior matrix, not a planned-capability",
            "chart. Each cell is a seeded, bounded baseline call of a public selector",
            "entry point. Numeric, sparse, and row-metadata axes use `n=32` rows and",
            "4 feature columns; the categorical fixture adds a string column (`p=5`);",
            "the datetime/timedelta fixture adds `when` and `elapsed` (`p=6`).",
            "Iteration, draw, and runtime knobs are reduced so the probes stay cheap;",
            "algorithm-routing and data-type acceptance/encoding defaults are left in",
            "place, with three explicit exceptions: stability uses a fixed `alpha=1.0`",
            "instead of automatic alpha search, CatBoost uses",
            '`algorithm="prediction"` with `prefilter_k=None` instead of its SHAP',
            "and prefilter defaults, and `ModelSelector` is constructed with",
            "`Ridge()` because the class requires an estimator (a disclosed probe",
            "baseline, not a library default). Warnings are captured for classification",
            "and are not copied into the table. The probes never change selector",
            "mathematics or public defaults to make a cell succeed.",
            "SIFT-specific terms are defined in the [glossary](glossary.md).",
            "",
            "Regenerate with:",
            "",
            "```bash",
            "python scripts/generate_data_type_matrix.py",
            "```",
            "",
            "## Legend",
            "",
            "| code | status | meaning |",
            "| --- | --- | --- |",
            "| `yes` | supported | the seeded, bounded baseline call completed |",
            "| `no` | rejected | the baseline call raised |",
            "| `cond` | conditional | the baseline call raised, and one documented enabling option succeeded |",
            "| `dep` | dependency-gated | installing the optional extra can unlock this axis |",
            "",
            "Enabling options used for `cond` cells:",
            "",
            '- categorical filters/Boruta: `cat_encoding="target_cv"` (in-library; no extra)',
            '- `KnockoffSelector` categorical: `cat_encoding="loo_logit"` (warns; `fdr_control=\'none\'`)',
            '- groups/time: `k="auto"` with `AutoKConfig(k_method="evaluate")` and the matching split strategy',
            "- `ModelSelector` categorical: width-preserving sklearn `OrdinalEncoder`",
            "  encoding with permutation importance on raw input columns",
            "  (estimator-dependent; not a library encoding default)",
            "- `ModelSelector` groups/time: searched `n_features_to_select` grid with the",
            "  default reusable group/time CV",
            "",
            "CatBoost cells publish the known post-install contract in every",
            "environment: `no` for ndarray, sparse, and datetime/timedelta; `dep`",
            "for DataFrame, categorical, weights, groups, and time. CatBoost-marked",
            "tests pin those post-install outcomes and do not rewrite the page.",
            "",
            "## Matrix",
            "",
            TABLE_START,
            render_table(cells),
            TABLE_END,
            "",
            "## Observed non-baseline cells",
            "",
            "Numeric ndarray/DataFrame successes and ordinary weight successes are",
            "omitted here; they are the `yes` cells in the matrix. Everything else is",
            "listed with a stable public-contract description. Raw exception type and",
            "message text is kept on the probe attempt for diagnostics and is not",
            "copied onto this page.",
            "",
            NOTES_START,
            render_notes(cells),
            NOTES_END,
            "",
            "## How to read the axes",
            "",
            "- **ndarray / DataFrame.** Dense numeric features. Named DataFrame columns",
            "  are the usual production path; positional ndarrays get generated `x0...`",
            "  names.",
            "- **categorical.** A string column beside numeric columns, with default",
            "  `cat_encoding`. `target_cv` is the in-library enabling option used for",
            "  `cond` cells. Filter selectors also accept `cat_encoding=\"onehot\"`",
            "  (atomic `{column}__{level}` blocks; not a matrix enabling option and",
            "  rejected on knockoffs/Boruta). `loo_logit` is also in-library (binary).",
            "  `loo` / `target` /",
            "  `james_stein` need `.[categorical]`. Function-style filters and all",
            "  Boruta entry points (including `BorutaSelector`) additionally require",
            "  `allow_full_data_target_encoding=True` for those legacy supervised",
            "  modes; sklearn filter selector classes and `KnockoffSelector` do not.",
            "  That extra path is not a matrix column. `ModelSelector` has no",
            "  categorical encoding default; the `cond` cell is a disclosed Ridge",
            "  pipeline, not a universal string rejection.",
            "- **sparse.** SciPy CSR input. Function and class routes are probed on",
            "  the same CSR axis. Low-level rejection messages differ; this matrix",
            "  normalizes them to one user-facing status and note.",
            "- **datetime/timedelta.** Feature columns, not row metadata. Convert them",
            "  to numeric features explicitly if they belong in the candidate set.",
            "- **weights.** `sample_weight=` on the public call, except `select_cached`,",
            "  whose weights are supplied to `build_cache` and stored on the cache.",
            "- **groups / time.** Row metadata arrays (or, for `smart_sample`, config",
            "  column names). A datetime `time=` array is metadata, not a feature.",
            "  Fixed-k filter functions and classes reject this context; automatic-k",
            "  evaluate splits accept it. `ModelSelector` with an explicit integer",
            "  count rejects unused `groups`/`time`; a searched count grid uses the",
            "  default reusable group/time CV.",
            "",
            "## Coverage limits",
            "",
            "- Fixtures are tiny and seeded. Completing a call is not a quality,",
            "  FDR, or runtime claim.",
            "- `permutation_importance` is probed with a fitted dtype-tolerant estimator",
            "  so categorical and datetime cells exercise SIFT rather than a numeric",
            "  model's `fit`. Support remains model-dependent. Sparse input is rejected",
            "  by SIFT independently of that estimator.",
            "- `ModelSelector` is probed with `Ridge()` as a disclosed constructor",
            "  baseline. Sparse and datetime/timedelta feature columns are rejected by",
            "  SIFT. Categorical `cond` uses a width-preserving sklearn encoding",
            "  pipeline plus permutation importance; that is not a claim about every",
            "  estimator and not a native CatBoost path.",
            "- `select_cached` is probed as `build_cache` plus `select_cached`. Weights",
            "  are passed to `build_cache`. Axes that are not arguments of",
            "  `select_cached` fail at the public call.",
            "- `smart_sample` reduces rows, not columns. Ndarray and sparse probes call",
            "  it with that object directly; the public function is documented to take",
            "  a DataFrame.",
            "- CatBoost ndarray, sparse, and datetime/timedelta cells are `no`.",
            "  Datetime/timedelta columns are not CatBoost feature types; convert",
            "  them to numeric features explicitly. DataFrame, categorical, weights,",
            "  groups, and time are `dep`. CatBoost-marked tests pin the post-install",
            "  outcomes. `select_boruta_shap` needs CatBoost for its default estimator;",
            "  without CatBoost an explicit non-CatBoost estimator still needs the",
            "  optional `shap` package, and categorical input still needs `target_cv`",
            "  before that SHAP check.",
            "- Low-level path/stopping-rule helpers (`select_k_*`, curve builders) and",
            "  standalone `build_cache` are outside this selector-entry-point matrix.",
            "  `sample_knockoffs` is a public generator, not a selector, and is out of",
            "  scope. `select_cached` is intentionally probed as `build_cache` plus",
            "  `select_cached`.",
            "- Multiclass helpers, Polars frames, sparse *output*, one-hot encoding,",
            "  and metadata-alias axes are out of scope. A 2-D numeric `y`",
            "  (`n×q`, `q≥2`) is not a matrix column: joint",
            "  multi-target CEFS+ is supported on `select_cefsplus`, `CEFSPlusSelector`,",
            "  `select_cached(method=\"cefsplus\")`, and `evaluate_feature_path`. Other",
            "  selectors reject it. Reusing one `FeatureCache` across separate 1-D `y`",
            "  calls is not joint multi-output support.",
            "- Complex dtypes, duplicate column labels, and empty `feature_names`",
            "  remain the sklearn-contract tests' job.",
        ]
    ) + "\n"


def expected_page() -> str:
    return render_page(probe_published())


def write_page(path: Path = DOC) -> Path:
    path.write_text(expected_page(), encoding="utf-8")
    return path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if docs/data-type-support.md does not match a live probe",
    )
    args = parser.parse_args(argv)
    try:
        page = expected_page()
    except Exception:
        traceback.print_exc()
        return 2
    if args.check:
        current = DOC.read_text(encoding="utf-8")
        if current != page:
            print(f"{DOC.relative_to(ROOT)} is stale; rerun without --check", file=sys.stderr)
            return 1
        return 0
    DOC.write_text(page, encoding="utf-8")
    print(f"wrote {DOC.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
